# Hands-on Lab: API Examples
## Random User and Fruityvice API Examples


Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruityvice API, using `requests` Python library
*   Load and use Open-Joke-API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [2]:
!pip install randomuser
!pip install pandas

Requirement already satisfied: randomuser in /Users/rahulkpkurup/Learning/Git Portfolio/CourseCodes/.venv/lib/python3.14/site-packages (1.6)
Requirement already satisfied: pandas in /Users/rahulkpkurup/Learning/Git Portfolio/CourseCodes/.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /Users/rahulkpkurup/Learning/Git Portfolio/CourseCodes/.venv/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rahulkpkurup/Learning/Git Portfolio/CourseCodes/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rahulkpkurup/Learning/Git Portfolio/CourseCodes/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Then, we will load the necessary libraries.

In [3]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [4]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [5]:
some_list = r.generate_users(10)

In [6]:
some_list

[<randomuser.RandomUser at 0x111219e50>,
 <randomuser.RandomUser at 0x111218f50>,
 <randomuser.RandomUser at 0x1091c7950>,
 <randomuser.RandomUser at 0x11129c050>,
 <randomuser.RandomUser at 0x10e838cb0>,
 <randomuser.RandomUser at 0x1112817b0>,
 <randomuser.RandomUser at 0x1112819d0>,
 <randomuser.RandomUser at 0x108e43a50>,
 <randomuser.RandomUser at 0x11124a550>,
 <randomuser.RandomUser at 0x10913d9a0>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [7]:
name = r.get_full_name()
name

'Samuel Lee'

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [8]:
for user in some_list:
    print (user.get_full_name()," : ",user.get_email())

Martins Peixoto  :  martins.peixoto@example.com
Bernard Duncan  :  bernard.duncan@example.com
Adam Bailey  :  adam.bailey@example.com
Noah Jones  :  noah.jones@example.com
Oscar Simon  :  oscar.simon@example.com
Jimmy Hernandez  :  jimmy.hernandez@example.com
Steve Lopez  :  steve.lopez@example.com
Gordon Banks  :  gordon.banks@example.com
Pinja Linna  :  pinja.linna@example.com
Evan Wilson  :  evan.wilson@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [9]:
## Write your code here
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/81.jpg
https://randomuser.me/api/portraits/men/75.jpg
https://randomuser.me/api/portraits/men/81.jpg
https://randomuser.me/api/portraits/men/73.jpg
https://randomuser.me/api/portraits/men/97.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/11.jpg
https://randomuser.me/api/portraits/men/59.jpg
https://randomuser.me/api/portraits/women/86.jpg
https://randomuser.me/api/portraits/men/70.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [10]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [11]:
def get_some_data():
    users=[]
    for user in RandomUser.generate_users(20):
        users.append({
        'Name':user.get_full_name(),
        'Gender':user.get_gender(),
        "City":user.get_city(),
        "State":user.get_state(),
        "Email":user.get_email(), 
        "DOB":user.get_dob(),
        "Picture":user.get_picture()
    })
    return pd.DataFrame(users)

get_some_data()

,Name,Gender,City,State,Email,DOB,Picture
0,Charles Martin,male,Blenheim,Taranaki,charles.martin@example.com,1954-08-23T20:36:24.840Z,https://randomuser.me/api/portraits/men/25.jpg
1,Asli Breukelman,female,Warnsveld,Gelderland,asli.breukelman@example.com,1945-07-15T23:50:18.419Z,https://randomuser.me/api/portraits/women/86.jpg
2,Mia Butler,female,Stirling,Merseyside,mia.butler@example.com,1952-07-23T14:28:55.848Z,https://randomuser.me/api/portraits/women/3.jpg
3,Veeti Justi,male,Polvijärvi,Åland,veeti.justi@example.com,1979-12-20T12:01:14.208Z,https://randomuser.me/api/portraits/men/13.jpg
4,Brittany Franklin,female,Carlow,Cork,brittany.franklin@example.com,1987-04-20T21:59:10.330Z,https://randomuser.me/api/portraits/women/71.jpg
5,Christoffer Kibsgaard,male,Follebu,Trøndelag,christoffer.kibsgaard@example.com,1982-01-09T12:41:57.263Z,https://randomuser.me/api/portraits/men/84.jpg
6,Nicholas Doyle,male,Tramore,Dún Laoghaire–Rathdown,nicholas.doyle@example.com,1945-07-05T23:18:42.910Z,https://randomuser.me/api/portraits/men/61.jpg
7,Ahmad Schütte,male,Heimbach,Bremen,ahmad.schutte@example.com,1951-08-24T00:10:41.159Z,https://randomuser.me/api/portraits/men/1.jpg
8,Freja Jørgensen,female,Ugerløse,Sjælland,freja.jorgensen@example.com,1992-12-18T00:41:51.306Z,https://randomuser.me/api/portraits/women/52.jpg
9,Julien Charles,male,Villeurbanne,Gironde,julien.charles@example.com,1973-12-17T01:40:31.771Z,https://randomuser.me/api/portraits/men/30.jpg
10,Beau Harris,male,Lower Hutt,Canterbury,beau.harris@example.com,1979-01-29T15:45:56.456Z,https://randomuser.me/api/portraits/men/74.jpg
11,بهاره حیدری,female,سنندج,مازندران,bhrh.hydry@example.com,1997-03-22T11:07:28.099Z,https://randomuser.me/api/portraits/women/93.jpg
12,Gregor Muller,male,Fischbach,Uri,gregor.muller@example.com,1986-06-20T14:16:48.744Z,https://randomuser.me/api/portraits/men/57.jpg
13,Vilma Pakkala,female,Eura,Tavastia Proper,vilma.pakkala@example.com,1990-08-06T03:45:20.186Z,https://randomuser.me/api/portraits/women/0.jpg
14,پوریا کامروا,male,سیرجان,اصفهان,pwry.khmrw@example.com,1974-04-25T01:52:54.729Z,https://randomuser.me/api/portraits/men/10.jpg
15,Sharon Hicks,female,Glasgow,North Yorkshire,sharon.hicks@example.com,1959-07-12T08:45:43.529Z,https://randomuser.me/api/portraits/women/17.jpg
16,Lionel Roussel,male,Kiesen,Valais,lionel.roussel@example.com,1960-05-25T08:36:19.364Z,https://randomuser.me/api/portraits/men/6.jpg
17,Pinja Arola,female,Toivakka,Northern Savonia,pinja.arola@example.com,1963-03-30T16:21:20.454Z,https://randomuser.me/api/portraits/women/77.jpg
18,Emerentiana Nederpelt,female,Hekendorp,Zuid-Holland,emerentiana.nederpelt@example.com,1997-10-22T03:32:59.643Z,https://randomuser.me/api/portraits/women/6.jpg
19,Levi Williams,male,Nelson,Auckland,levi.williams@example.com,1975-03-01T06:12:07.473Z,https://randomuser.me/api/portraits/men/33.jpg

In [12]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Jeffrey Cook,male,Norwich,County Armagh,jeffrey.cook@example.com,1991-06-14T20:29:13.145Z,https://randomuser.me/api/portraits/men/72.jpg
1,Sienna Chen,female,Porirua,Auckland,sienna.chen@example.com,1981-02-08T10:40:30.925Z,https://randomuser.me/api/portraits/women/95.jpg
2,Beau Wood,male,Timaru,Otago,beau.wood@example.com,1964-02-13T01:33:38.163Z,https://randomuser.me/api/portraits/men/22.jpg
3,Eleah Halden,female,Smestad,Hedmark,eleah.halden@example.com,1983-01-11T13:15:36.479Z,https://randomuser.me/api/portraits/women/65.jpg
4,Siham Dinh,female,Skånevik,Description,siham.dinh@example.com,1978-05-23T06:54:24.621Z,https://randomuser.me/api/portraits/women/11.jpg
5,Juho Moilanen,male,Janakkala,Central Finland,juho.moilanen@example.com,1951-08-25T06:05:31.901Z,https://randomuser.me/api/portraits/men/17.jpg
6,Jason Franklin,male,Carrick-on-Suir,Kerry,jason.franklin@example.com,1946-09-17T11:39:53.532Z,https://randomuser.me/api/portraits/men/0.jpg
7,Fred Alvarez,male,Queanbeyan,Tasmania,fred.alvarez@example.com,1955-08-07T10:59:41.708Z,https://randomuser.me/api/portraits/men/82.jpg
8,Jeffrey Montgomery,male,Ballarat,Australian Capital Territory,jeffrey.montgomery@example.com,1968-12-09T04:53:56.641Z,https://randomuser.me/api/portraits/men/25.jpg
9,Felix Evans,male,Napier,Marlborough,felix.evans@example.com,1954-02-11T22:47:47.792Z,https://randomuser.me/api/portraits/men/79.jpg

In [13]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [25]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using `requests.get("url")` function. The data is in a json format.

In [15]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [16]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [17]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [26]:
df2 = pd.json_normalize(results)

In [27]:
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [29]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])
cherry

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [36]:
df2[df2['nutritions.protein']==df2['nutritions.protein'].max()]

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.0,4.3,17.0,15.0

In [42]:
sorted_df = df2.sort_values(by='nutritions.protein',ascending=False)
sorted_df

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [48]:
# Write your code here
cal_banana = df2.loc[df2['name'] == 'Banana']
calories = cal_banana.iloc[0]['nutritions.carbohydrates']
calories

np.float64(22.0)

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get("url")` function, load the data from the URL.

In [50]:
# Write your code here
data2 = requests.get('https://official-joke-api.appspot.com/jokes/ten')
data2

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
```

</details>

2. Retrieve results using `json.loads()` function.

In [51]:
# Write your code here
results2 = json.loads(data2.text)
results2

[{'type': 'general',
  'setup': 'Have you ever heard of a music group called Cellophane?',
  'punchline': 'They mostly wrap.',
  'id': 109},
 {'type': 'general',
  'setup': 'Why does a chicken coop only have two doors?',
  'punchline': 'Because if it had four doors it would be a chicken sedan.',
  'id': 356},
 {'type': 'general',
  'setup': 'Why did the cookie cry?',
  'punchline': 'Because his mother was a wafer so long',
  'id': 320},
 {'type': 'general',
  'setup': 'Why did the scarecrow win an award?',
  'punchline': 'Because he was outstanding in his field.',
  'id': 333},
 {'type': 'general',
  'setup': 'Where did you learn to make ice cream?',
  'punchline': 'Sunday school.',
  'id': 283},
 {'type': 'general',
  'setup': 'Why are skeletons so calm?',
  'punchline': 'Because nothing gets under their skin.',
  'id': 305},
 {'type': 'general',
  'setup': 'Where does batman go to the bathroom?',
  'punchline': 'The batroom.',
  'id': 290},
 {'type': 'general',
  'setup': 'Why did the burglar hang his mugshot on the wall?',
  'punchline': 'To prove that he was framed!',
  'id': 317},
 {'type': 'programming',
  'setup': 'Why do Java programmers wear glasses?',
  'punchline': "Because they don't C#.",
  'id': 34},
 {'type': 'general',
  'setup': 'How do hens stay fit?',
  'punchline': 'They always egg-cercise!',
  'id': 118}]

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3. Convert json data into *pandas* data frame. Drop the type and id columns.

In [52]:
# Write your code here
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3

,setup,punchline
0,Have you ever heard of a music group called Ce...,They mostly wrap.
1,Why does a chicken coop only have two doors?,Because if it had four doors it would be a chi...
2,Why did the cookie cry?,Because his mother was a wafer so long
3,Why did the scarecrow win an award?,Because he was outstanding in his field.
4,Where did you learn to make ice cream?,Sunday school.
5,Why are skeletons so calm?,Because nothing gets under their skin.
6,Where does batman go to the bathroom?,The batroom.
7,Why did the burglar hang his mugshot on the wall?,To prove that he was framed!
8,Why do Java programmers wear glasses?,Because they don't C#.
9,How do hens stay fit?,They always egg-cercise!

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3
```

</details>