# SQL for Data Science Advanced Filtering

This notebook covers:
- In Operator
- AND / OR / NOT
- LIKE and Wildcards
- Pandas Equivalent

# Load SQL Extension

In [1]:
%load_ext sql

# Connect to PostgresSQL

In [2]:
%sql postgresql://localhost/startup_commerce_db

# Create Tables

In [3]:
%%sql
create table employees (
    emp_id int primary key,
    name text,
    department text,
    salary int,
    city text
);

 * postgresql://localhost/startup_commerce_db
Done.

[]

# Insert Data

In [7]:
%%sql
insert into employees values
(1, 'Alice', 'Engineering', 70000, 'Delhi'),
(2, 'Bob', 'HR', 50000, 'Mumbai'),
(3, 'Charlie', 'Engineering', 80000, 'Delhi'),
(4, 'David', 'Finance', 60000, 'Chennai'),
(5, 'Eva', 'HR', 55000, 'Bangalore'),
(6, 'Frank', 'Engineering', 90000, 'Mumbai'),
(7, 'George', 'Finance', 65000, 'Delhi');

 * postgresql://localhost/startup_commerce_db
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "employees_pkey"
DETAIL:  Key (emp_id)=(1) already exists.

[SQL: insert into employees values
(1, 'Alice', 'Engineering', 70000, 'Delhi'),
(2, 'Bob', 'HR', 50000, 'Mumbai'),
(3, 'Charlie', 'Engineering', 80000, 'Delhi'),
(4, 'David', 'Finance', 60000, 'Chennai'),
(5, 'Eva', 'HR', 55000, 'Bangalore'),
(6, 'Frank', 'Engineering', 90000, 'Mumbai'),
(7, 'George', 'Finance', 65000, 'Delhi');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [8]:
%%sql 
select * from employees;

 * postgresql://localhost/startup_commerce_db
7 rows affected.

[(1, 'Alice', 'Engineering', 70000, 'Delhi'),
 (2, 'Bob', 'HR', 50000, 'Mumbai'),
 (3, 'Charlie', 'Engineering', 80000, 'Delhi'),
 (4, 'David', 'Finance', 60000, 'Chennai'),
 (5, 'Eva', 'HR', 55000, 'Bangalore'),
 (6, 'Frank', 'Engineering', 90000, 'Mumbai'),
 (7, 'George', 'Finance', 65000, 'Delhi')]

# Convert into Pandas

In [9]:
import pandas as pd
result = %sql select * from employees;
df = result.DataFrame()
df.head(7)

 * postgresql://localhost/startup_commerce_db
7 rows affected.

   emp_id     name   department  salary       city
0       1    Alice  Engineering   70000      Delhi
1       2      Bob           HR   50000     Mumbai
2       3  Charlie  Engineering   80000      Delhi
3       4    David      Finance   60000    Chennai
4       5      Eva           HR   55000  Bangalore
5       6    Frank  Engineering   90000     Mumbai
6       7   George      Finance   65000      Delhi

# IN Operator

In [5]:
%%sql
select * from employees where city in ('Delhi','Mumbai');

 * postgresql://localhost/startup_commerce_db
5 rows affected.

[(1, 'Alice', 'Engineering', 70000, 'Delhi'),
 (2, 'Bob', 'HR', 50000, 'Mumbai'),
 (3, 'Charlie', 'Engineering', 80000, 'Delhi'),
 (6, 'Frank', 'Engineering', 90000, 'Mumbai'),
 (7, 'George', 'Finance', 65000, 'Delhi')]

In [10]:
df[df['city'].isin(['Delhi','Mumbai'])]

   emp_id     name   department  salary    city
0       1    Alice  Engineering   70000   Delhi
1       2      Bob           HR   50000  Mumbai
2       3  Charlie  Engineering   80000   Delhi
5       6    Frank  Engineering   90000  Mumbai
6       7   George      Finance   65000   Delhi

# AND Operator

In [12]:
%%sql
select * from employees where department='Engineering' and salary > 75000;

 * postgresql://localhost/startup_commerce_db
2 rows affected.

[(3, 'Charlie', 'Engineering', 80000, 'Delhi'),
 (6, 'Frank', 'Engineering', 90000, 'Mumbai')]

In [14]:
df[(df['department']=='Engineering') & (df['salary']>75000)]

   emp_id     name   department  salary    city
2       3  Charlie  Engineering   80000   Delhi
5       6    Frank  Engineering   90000  Mumbai

# OR Operator

In [22]:
%%sql
select * from employees where department='HR' or salary > 80000;

 * postgresql://localhost/startup_commerce_db
3 rows affected.

[(2, 'Bob', 'HR', 50000, 'Mumbai'),
 (5, 'Eva', 'HR', 55000, 'Bangalore'),
 (6, 'Frank', 'Engineering', 90000, 'Mumbai')]

In [25]:
df[(df['department']=='HR') | (df['salary']>80000)]

   emp_id   name   department  salary       city
1       2    Bob           HR   50000     Mumbai
4       5    Eva           HR   55000  Bangalore
5       6  Frank  Engineering   90000     Mumbai

# NOT Operator

In [21]:
%%sql
select * from employees where not department = 'HR'

 * postgresql://localhost/startup_commerce_db
5 rows affected.

[(1, 'Alice', 'Engineering', 70000, 'Delhi'),
 (3, 'Charlie', 'Engineering', 80000, 'Delhi'),
 (4, 'David', 'Finance', 60000, 'Chennai'),
 (6, 'Frank', 'Engineering', 90000, 'Mumbai'),
 (7, 'George', 'Finance', 65000, 'Delhi')]

In [26]:
df[df['department']!='HR']

   emp_id     name   department  salary     city
0       1    Alice  Engineering   70000    Delhi
2       3  Charlie  Engineering   80000    Delhi
3       4    David      Finance   60000  Chennai
5       6    Frank  Engineering   90000   Mumbai
6       7   George      Finance   65000    Delhi

# LIKE + Wildcards

In [27]:
%%sql
select * from employees where name like 'A%'

 * postgresql://localhost/startup_commerce_db
1 rows affected.

[(1, 'Alice', 'Engineering', 70000, 'Delhi')]

In [29]:
df[df['name'].str.startswith('A')]

   emp_id   name   department  salary   city
0       1  Alice  Engineering   70000  Delhi