# Filtering, Ranges, NULLs

## Load SQL Extension

In [1]:
%load_ext sql

## Connect to PostgresSQL

In [2]:
%sql postgresql://localhost/startup_commerce_db

## Create Tables

In [4]:
%%sql
create table users (
    user_id SERIAL primary key,
    name text,
    email text,
    city text
);

 * postgresql://localhost/startup_commerce_db
Done.

[]

In [6]:
%%sql
create table products (
    product_id SERIAL primary key,
    product_name text,
    price float
);

 * postgresql://localhost/startup_commerce_db
Done.

[]

In [9]:
%%sql
create table orders (
    order_id SERIAL primary key,
    user_id int,
    product_id int,
    amount float,
    order_date date,
    foreign key (user_id) references users (user_id),
    foreign key (product_id) references products (product_id)
);

 * postgresql://localhost/startup_commerce_db
Done.

[]

## Insert Data

In [10]:
%%sql
insert into users (name, email,city) values
('Alice', 'ali@gmail.com','Delhi'),
('Bob', NULL,'Mumbai'),
('charlie','charlie@gmail.com','Bangalore'),
('David', NULL, 'Delhi');

 * postgresql://localhost/startup_commerce_db
4 rows affected.

[]

In [11]:
%%sql
insert into products (product_name, price) values
('MacBook', 10000000),
('iPhone',300000),
('iPad', 500000);

 * postgresql://localhost/startup_commerce_db
3 rows affected.

[]

In [12]:
%%sql
insert into orders (user_id, product_id, amount,order_date) values
(1,1,75000,'2024-01-10'),
(2,2,30000,'2024-02-15'),
(3,3,20000,'2024-03-20');

 * postgresql://localhost/startup_commerce_db
3 rows affected.

[]

In [13]:
%%sql
select * from users;

 * postgresql://localhost/startup_commerce_db
4 rows affected.

[(1, 'Alice', 'ali@gmail.com', 'Delhi'),
 (2, 'Bob', None, 'Mumbai'),
 (3, 'charlie', 'charlie@gmail.com', 'Bangalore'),
 (4, 'David', None, 'Delhi')]

In [14]:
%%sql
select * from products;

 * postgresql://localhost/startup_commerce_db
3 rows affected.

[(1, 'MacBook', 10000000.0), (2, 'iPhone', 300000.0), (3, 'iPad', 500000.0)]

In [15]:
%%sql
select * from orders;

 * postgresql://localhost/startup_commerce_db
3 rows affected.

[(1, 1, 1, 75000.0, datetime.date(2024, 1, 10)),
 (2, 2, 2, 30000.0, datetime.date(2024, 2, 15)),
 (3, 3, 3, 20000.0, datetime.date(2024, 3, 20))]

## WHERE

In [17]:
%%sql
select * from users where city='Delhi';

 * postgresql://localhost/startup_commerce_db
2 rows affected.

[(1, 'Alice', 'ali@gmail.com', 'Delhi'), (4, 'David', None, 'Delhi')]

## BETWEEN

In [19]:
%%sql 
select * from products where price between 20000 and 500000;

 * postgresql://localhost/startup_commerce_db
2 rows affected.

[(2, 'iPhone', 300000.0), (3, 'iPad', 500000.0)]

## NULL

In [20]:
%%sql
select * from users where email is NULL;

 * postgresql://localhost/startup_commerce_db
2 rows affected.

[(2, 'Bob', None, 'Mumbai'), (4, 'David', None, 'Delhi')]

## Convert to Pandas

In [21]:
import pandas as pd

In [27]:
users = %sql select * from users;
users_df = users.DataFrame()
users_df.head()

 * postgresql://localhost/startup_commerce_db
4 rows affected.

   user_id     name              email       city
0        1    Alice      ali@gmail.com      Delhi
1        2      Bob                NaN     Mumbai
2        3  charlie  charlie@gmail.com  Bangalore
3        4    David                NaN      Delhi

## Pandas WHERE

In [32]:
users_df[users_df['city']=='Delhi']

   user_id   name          email   city
0        1  Alice  ali@gmail.com  Delhi
3        4  David            NaN  Delhi

## Panadas BETWEEN

In [33]:
products = %sql select * from products;
products_df = products.DataFrame()
products_df[products_df['price'].between(20000,500000)]

 * postgresql://localhost/startup_commerce_db
3 rows affected.

   product_id product_name     price
1           2       iPhone  300000.0
2           3         iPad  500000.0

## Pandas NULL

In [34]:
users_df[users_df['email'].isnull()]

   user_id   name email    city
1        2    Bob   NaN  Mumbai
3        4  David   NaN   Delhi

# Summary
A realistic commerce-based schema is designed, consisting of interconnected tables representing users, products, and orders. The notebook emphasizes core SQL filtering operations, including conditional selection using WHERE, range-based filtering with BETWEEN, handling missing data using IS NULL and IS NOT NULL, and identifying non-matching records through LEFT JOIN operations.